//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmerScheme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bid_history
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bid_history()
        {
            this.transaction_history = new HashSet<transaction_history>();
        }
    
        public int bid_id { get; set; }
        public Nullable<int> request_id { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<System.TimeSpan> bidding_time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaction_history> transaction_history { get; set; }
        public virtual crop crop { get; set; }
        public virtual user_information user_information { get; set; }
    }
}
