//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmerScheme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class insurance_claim
    {
        public int claim_id { get; set; }
        public Nullable<int> policy_no { get; set; }
        public Nullable<System.DateTime> date_of_loss { get; set; }
        public Nullable<System.DateTime> cause_of_loss { get; set; }
        public Nullable<System.DateTime> claim_date { get; set; }
        public bool insurance_claim_approval_status { get; set; }
    
        public virtual insurance insurance { get; set; }
    }
}
