//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmerScheme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class crop
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public crop()
        {
            this.bid_history = new HashSet<bid_history>();
            this.transaction_history = new HashSet<transaction_history>();
        }
    
        public int request_id { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> crop_id { get; set; }
        public string fertilizer_type { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> base_price { get; set; }
        public bool crop_approval_status { get; set; }
        public bool bid_approval_status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bid_history> bid_history { get; set; }
        public virtual crop_information crop_information { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transaction_history> transaction_history { get; set; }
        public virtual user_information user_information { get; set; }
    }
}
