//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmerScheme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class insurance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public insurance()
        {
            this.insurance_claim = new HashSet<insurance_claim>();
        }
    
        public int policy_no { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> land_id { get; set; }
        public string season { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> crop_id { get; set; }
        public Nullable<int> sum_insured { get; set; }
        public string insurance_company { get; set; }
        public Nullable<int> premium_amount { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public bool expiry_status { get; set; }
        public bool insurance_approval_status { get; set; }
    
        public virtual crop_information crop_information { get; set; }
        public virtual land_details land_details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<insurance_claim> insurance_claim { get; set; }
        public virtual user_information user_information { get; set; }
    }
}
