//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FarmerScheme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction_history
    {
        public int transaction_id { get; set; }
        public Nullable<int> request_id { get; set; }
        public Nullable<int> bid_id { get; set; }
    
        public virtual bid_history bid_history { get; set; }
        public virtual crop crop { get; set; }
    }
}
